### ISSUE TITLE
Seems that it stop working.

### ISSUE THREAD

**Issue by leozanelato** [MrGForse/BF3-Limited-Edition-B2K-Fix#2]
Used it yesterday, works like a charm. But now today seems to not work anymore.

I use google chrome 84, with Ublock and tampermonkey script. 

The issue is the battlelog from bf3 randomly refreshes the page and when I click join to a server nothing happens. When I disable the script from tampermonkey the popup that I dont have Back to Karkand comes up. Seems that half of the script is working.

And last but not least, thank a lot you the devs for the script that I can finally play again after 4 or 5 years of this Back to Karkand popup. 

If there is a log I can give you from the script please tell me how I do it.

Edit: the random reboot is the script doing its thing.
Tried to install the new Microsoft Edge (Chromium) from scratch and the same problem occur. All set, the ublock origin block list, the tampermonkey script too, but the exacly same problem occur, when i click join server nothing happens. And now I copied a log from the console atached.

[console log.txt](https://github.com/MrGForse/BF3-Limited-Edition-B2K-Fix/files/5113351/console.log.txt)

Edit 2 : The console is from history tab in server browser from Edge chromium. As I said I have just installed and tried to install the B2K script.

And sorry if I am doing something wrong or saying, I am just trying to help as this script made me feel very happy that I can play this game again with I love the most, and the english isnt my primary language, so sorry if you dont understand something.

**Comment by GeorgeForse** [comment]
Just got back from holiday, so I'll look at this now. Could be related to CORS, I'll do some further debugging.

**Comment by GeorgeForse** [comment]
Small update, just checked myself and it seems that EA/DICE have applied the fix to their CDN. Therefore, this fix is now redundant and no longer necessary.

Enjoy!

**Comment by GeorgeForse** [comment]
Issue fixed officially by software vendor. Script now redundant.
